### ISSUE TITLE
Ressources donwload

### ISSUE THREAD

**Issue by val3riefr** [K-E-N-W-A-Y/Skillshare-DL#12] opened 2021-01-03 09:53 UTC
Hi, the downloader works, however how can we get the ressources files?

**Comment by K-E-N-W-A-Y** [comment] 2021-01-03 11:42
duplicate of #11

**Closed by K-E-N-W-A-Y** 2021-01-03 11:42 UTC

**Comment by ANASABDIALI** [comment] 2021-01-30 14:26
Thanks you 100%
Many students like me are greeting you from Somalia 🇸🇴♥️.
I really appreciate your for the great work you have done.
I don't know what to say .
Thank thanks
